server:
  port: 8080
spring:
  application:
    name: sm3-api-gateway
  zipkin:
    base-url: http://zipkin:9411
  cloud:
    gateway:
      routes:
        - id: sm3-customer-service
          uri: lb://SM3-CUSTOMER-SERVICE
          predicates: Path=/api/v1/customer/**

eureka:
  client:
    service-url:
      defaultZone: http://sm3-eureka-server:8761/eureka
